# Change these first
owner: hnguyen1910 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403 # Cloudflare bot protect
  - name: Link Shortener (basic)
    url: https://r.tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403 
  - name: Link Shortener (discord.gg links)
    url: https://d.tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403 
  - name: Files
    url: https://fs.tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403 
  - name: NoPaste
    url: https://nopaste.tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403 
  - name: Discord Bot
    url: https://fwt.tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: This status page
    url: https://status.tinvn.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tinvn.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HNStatus
  introTitle: "This page powered entirely by GitHub."
  introMessage: :)
  navbar:
    - title: Home
      href: https://tinvn.eu.org\
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  js: "window.onload = function() { alert('Hello! Welcome to my status page!') }"
user-agent: hnguyen1910

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
